site_name: Tourmaline
repo_url: https://github.com/protoncr/tourmaline
edit_uri: https://github.com/protoncr/tourmaline/tree/master/docs/
site_url: https://tourmaline.dev

theme:
  name: material
  palette:
    scheme: default
    primary: teal
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  icon:
    logo: fontawesome/brands/telegram
    repo: fontawesome/brands/github
  favicon: images/logo.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - macros:
      modules:
        - mkdocstrings.handlers.crystal.macros

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - deduplicate-toc
  - admonition
  - def_list
  - toc:
      permalink: "#"

extra:
  version:
    method: mike
