name: Specs

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal-version: [1.0.0]
    
    steps:
    - uses: actions/checkout@v2
    - uses: oprypin/install-crystal@v1
      with:
        crystal: ${{ matrix.crystal-version }}
    
    - name: Install dependencies
      run: shards install --ignore-crystal-version
    
    - name: Format code
      run: crystal tool format && git diff --exit-code
    
    - name: Run tests
      run: crystal spec
